{{- if .Values.ragService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cb-platform.serviceName" (dict "ctx" . "component" "rag") }}
  labels:
    {{- include "cb-platform.componentLabels" (dict "ctx" . "component" "rag") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ragService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cb-platform.selectorLabels" (dict "ctx" . "component" "rag") | nindent 4 }}
{{- end }}
